Develop
MlynorikAlina/sql_requests pull request #1
Opened 2020-10-27 16:35 UTC by MlynorikAlina

2020-10-28 20:33 UTC, VeronikaYastr requested changes

2020-10-28 20:33 UTC, VeronikaYastr commented on src/main/com/bsu/Main.java
> +        if (data[0].equals("select") && data[1].equals("*") && data[2].equals("from")) {
Нет проверки на количество элементов в data

2020-10-28 20:33 UTC, VeronikaYastr commented on src/main/com/bsu/Main.java
> +                if (data[i].equals("where")) {
Можно вынести ключевые слова в константы

2020-11-01 18:09 UTC, MlynorikAlina commented on src/main/com/bsu/Main.java
> +        if (data[0].equals("select") && data[1].equals("*") && data[2].equals("from")) {
done

2020-11-01 18:29 UTC, MlynorikAlina commented on src/main/com/bsu/Main.java
> +                if (data[i].equals("where")) {
done

2021-02-09 12:00 UTC, merged